### ISSUE TITLE
Invalid MAC Address format

### ISSUE THREAD

**Issue by Nibba2018** [nsmfoo/antivmdetection#55] opened 2020-06-04 08:07 UTC
Hi I am facing the following issue while running the `.sh` script, can you help me out?

```bash
VBoxManage: error: Invalid MAC address format
VBoxManage: error: Details: code NS_ERROR_INVALID_ARG (0x80070057), component NetworkAdapterWrap, interface INetworkAdapter, callee nsISupports
VBoxManage: error: Context: "COMSETTER(MACAddress)(Bstr(ValueUnion.psz).raw())" at line 2068 of file VBoxManageModifyVM.cpp
```

**Comment by looi-wh** [comment] 2020-07-29 10:26
apparently his mac address generator had some issues. just adjust the mac address in the .sh file to something valid

**Comment by nsmfoo** [comment] 2020-07-29 20:13
The issue is because, generating the new MAC address based on the original MAC address, on some hardware come out faulty. This should obviously be caught. Sometimes just re-running the script will generate a new one that works, but I agree it's a bit tedious. I will try to finally fix this issue

/Mikael

**Comment by nsmfoo** [comment] 2020-11-20 11:53
Very late reply. I just pushed a fix that should mitigate this issue. Please test and  if the fix was not enough, please re-open this issue and I will take a second look at it =)

**Closed as completed by nsmfoo** 2020-11-20 11:53 UTC
Labels: bug
